language: python
matrix:
  include:
    - python: "3.5"
    - python: "3.6"
    - python: "3.7"
      dist: xenial  # required for Python >= 3.7
install: pip install -r requirements.txt
script: pytest
