# https://github.com/brandtbucher/travis-python-matrix

# CPython 3.7.3 / CPython 3.6.8
# Ubuntu Xenial 16.04 / Windows 10 (64-bit) / Windows 10 (32-bit) / macOS 10.14 (Mojave)

# Just comment out any matrix entries you don't need.

language: shell

matrix:

  include:

    - name: CPython 3.7.3 on Ubuntu 16.04 (Xenial Xerus)
      language: python
      os: linux
      dist: xenial
      python: 3.7.3

    - name: CPython 3.6.8 on Ubuntu 16.04 (Xenial Xerus)
      language: python
      os: linux
      dist: xenial
      python: 3.6.8

    - name: CPython 3.7.3 on Windows 10 (64-bit)
      language: shell
      os: windows
      before_install:
        - export PATH=/c/Python37:/c/Python37/Scripts:$PATH
        - choco install python --version 3.7.3

    - name: CPython 3.6.8 on Windows 10 (64-bit)
      language: shell
      os: windows
      before_install:
        - export PATH=/c/Python36:/c/Python36/Scripts:$PATH
        - choco install python --version 3.6.8

    - name: CPython 3.7.3 on Windows 10 (32-bit)
      language: shell
      os: windows
      before_install:
        - export PATH=/c/Python37:/c/Python37/Scripts:$PATH
        - choco install python --version 3.7.3 --x86

    - name: CPython 3.6.8 on Windows 10 (32-bit)
      language: shell
      os: windows
      before_install:
        - export PATH=/c/Python36:/c/Python36/Scripts:$PATH
        - choco install python --version 3.6.8 --x86

    - name: CPython 3.7.3 on macOS 10.14 (Mojave)
      language: shell
      os: osx
      osx_image: xcode10.2
      before_install:
        - export CFLAGS="-I$(xcrun --show-sdk-path)/usr/include"
        - export PATH=/Users/travis/.pyenv/shims:$PATH PYENV_VERSION=3.7.3
        - pyenv install $PYENV_VERSION

    - name: CPython 3.6.8 on macOS 10.14 (Mojave)
      language: shell
      os: osx
      osx_image: xcode10.2
      before_install:
        - export CFLAGS="-I$(xcrun --show-sdk-path)/usr/include"
        - export PATH=/Users/travis/.pyenv/shims:$PATH PYENV_VERSION=3.6.8
        - pyenv install $PYENV_VERSION

    - name: mypy
      python: 3.7
      dist: xenial
      language: python
      script: mypy --strict

# Change anything below to suit your CI needs.
# Python and pip exectuables are just named "python" and "pip" on all platforms!

install: pip install -r requirements-test.txt

script: pytest --cov=static_frame

after_success: codecov
