name: Quality

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8

      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install wheel==0.35.1
        pip install numpy==1.16.5
        pip install Cython==0.29.13
        pip install setuptools==41.2.0
        pip install -r requirements-test.txt

    - name: Invoke Quality
      run: inv quality
